While compiling mutt the autotools want to compile and execute
makedoc. Since that will not work with noux.mk we remove the doc
subdir.
--- a/Makefile.am
+++ b/Makefile.am
@@ -9,7 +9,7 @@ IMAP_SUBDIR = imap
 IMAP_INCLUDES = -I$(top_srcdir)/imap
 endif
 
-SUBDIRS = m4 po intl doc contrib $(IMAP_SUBDIR)
+SUBDIRS = m4 po intl contrib $(IMAP_SUBDIR)
 
 bin_SCRIPTS = muttbug flea @SMIMEAUX_TARGET@
 
diff --git a/Makefile.in b/Makefile.in
index 57a2176..13537fb 100644
--- a/Makefile.in
+++ b/Makefile.in
@@ -259,7 +259,7 @@ am__define_uniq_tagged_files = \
 ETAGS = etags
 CTAGS = ctags
 CSCOPE = cscope
-DIST_SUBDIRS = m4 po intl doc contrib imap
+DIST_SUBDIRS = m4 po intl contrib imap
 DISTFILES = $(DIST_COMMON) $(DIST_SOURCES) $(TEXINFOS) $(EXTRA_DIST)
 distdir = $(PACKAGE)-$(VERSION)
 top_distdir = $(distdir)
@@ -451,7 +451,7 @@ top_srcdir = @top_srcdir@
 AUTOMAKE_OPTIONS = 1.6 foreign
 @BUILD_IMAP_TRUE@IMAP_SUBDIR = imap
 @BUILD_IMAP_TRUE@IMAP_INCLUDES = -I$(top_srcdir)/imap
-SUBDIRS = m4 po intl doc contrib $(IMAP_SUBDIR)
+SUBDIRS = m4 po intl contrib $(IMAP_SUBDIR)
 bin_SCRIPTS = muttbug flea @SMIMEAUX_TARGET@
 @BUILD_HCACHE_TRUE@HCVERSION = hcversion.h
 BUILT_SOURCES = keymap_defs.h patchlist.c reldate.h conststrings.c $(HCVERSION)
