#
# This run-script executes rsyslogd in Qemu and processes messages from
# a test component while sending these to a remote rsyslogd running
# an the host via UDP. The rsyslogd has to be configured as follows
#
#   module(load="imudp")
#   input(type="imudp" port="2342")
#
#   action(type="omfile" File="/dev/stdout")
#
# for the run-script to work. It can be started with
#   rsyslogd -i /tmp/rsyslogd.pid -n -f rsyslogd.conf

# The log is written to an EXT2 file-system on an NVMe device. The
# disk-image will be created once and is re-used between runs.
#

assert {[have_spec x86_64]}
assert {[have_spec nova]}

set mke2fs [installed_command mke2fs]
set dd     [installed_command dd]

if {![file exists bin/rsyslog-ext2.raw]} {
	puts "Create and format disk-image"
	catch { exec $dd if=/dev/zero of=bin/rsyslog-ext2.raw bs=1M count=16 }
	catch { exec $mke2fs -F bin/rsyslog-ext2.raw }
}


create_boot_directory

import_from_depot [depot_user]/src/[base_src] \
                  [depot_user]/src/acpi \
                  [depot_user]/src/init \
                  [depot_user]/src/libc \
                  [depot_user]/src/nic_router \
                  [depot_user]/src/nvme \
                  [depot_user]/src/openssl \
                  [depot_user]/src/pc_nic \
                  [depot_user]/src/pci_decode \
                  [depot_user]/src/platform \
                  [depot_user]/src/posix \
                  [depot_user]/src/report_rom \
                  [depot_user]/src/vfs \
                  [depot_user]/src/vfs_import \
                  [depot_user]/src/vfs_jitterentropy \
                  [depot_user]/src/vfs_lwip \
                  [depot_user]/src/vfs_pipe \
                  [depot_user]/src/vfs_rump \
                  [depot_user]/src/zlib \
                  [depot_user]/pkg/system_rtc-[board] \
                  [depot_user]/src/libestr/0.1.11-2026-04-22 \
                  [depot_user]/src/libfastjson/1.2304.0-2026-04-22 \
                  [depot_user]/src/rsyslog/8.2502.0-2026-04-22

build { lib/libc test/rsyslog }

#
# Generate config
#
append config {
config | verbose: yes
+ parent-provides
  + service CPU
  + service IO_MEM
  + service IO_PORT
  + service IRQ
  + service LOG
  + service PD
  + service RM
  + service ROM

+ default-route
  + any-service
    + parent
    + any-child

+ default | caps: 100 | ram: 1M

+ start timer
  + provides | + service Timer

+ start system_rtc | caps: 400 | ram: 6M
  + binary init
  + provides
    + service Rtc
    + service Report
  + route
    + service ROM     | label: config | + parent | label: system_rtc.config
    + service Timer                   | + child timer
    + service CPU                     | + parent
    + service IO_MEM                  | + parent
    + service IO_PORT                 | + parent
    + service IRQ                     | + parent
    + service LOG                     | + parent
    + service PD                      | + parent
    + service RM                      | + parent
    + service ROM                     | + parent

+ start drivers_reports | caps: 70
  + binary report_rom
  + provides
    + service ROM
    + service Report
  + config | verbose: no
    + policy | label:  pci_decode -> system | report: acpi -> acpi
    + policy | label:  platform -> devices  | report: pci_decode -> devices
  + route
    + any-service
      + parent
      + any-child

+ start acpi | caps: 350 | ram: 6M
  + route
    + service Report | + child drivers_reports
    + any-service
      + parent
      + any-child

+ start pci_decode | caps: 350
  + route
    + service ROM    | label: system | + child drivers_reports
    + service Report                 | + child drivers_reports
    + any-service
      + parent
      + any-child

+ start platform | caps: 400 | ram: 4M | managing_system: yes
  + provides | + service Platform
  + config
    + report | devices: yes
    + policy | label_prefix: nvme               | + pci | class: NVME
    + policy | label_prefix: pc_nic | info: yes | + pci | class: ETHERNET
  + route
    + service ROM    | label: devices | + child drivers_reports
    + service Report                  | + child drivers_reports
    + any-service
      + parent
      + any-child

+ start nvme | caps: 100 | ram: 4M
  + provides | + service Block
  + config
    + policy | label_prefix: vfs | writeable: yes
  + route
    + service Platform | + child platform
    + service Timer    | + child timer
    + any-service      | + parent

+ start pc_nic | caps: 120 | ram: 16M | priority: -1
  + config | ld_verbose: yes
+ start nic_router | caps: 150 | ram: 8M
  + provides
    + service Nic
    + service Uplink
  + config | verbose:                   no
           | verbose_domain_state:      yes
           | dhcp_discover_timeout_sec: 10
           | dhcp_request_timeout_sec:  6
    + policy | label_prefix: pc_nic | domain: uplink
    + policy | label_prefix: vfs    | domain: downlink
    + domain uplink
      | verbose_packets:     no
      | verbose_packet_drop: no
      | icmp_echo_server:    yes
      + nat | domain: downlink | tcp-ports: 100 | udp-ports: 100
    + domain downlink
      | verbose_packets:     no
      | verbose_packet_drop: no
      | interface:           10.0.3.1/24
      + dhcp-server | ip_first: 10.0.3.2 | ip_last: 10.0.3.2
      + tcp | dst: 0.0.0.0/0 | + permit-any | domain: uplink
      + udp | dst: 0.0.0.0/0 | + permit-any | domain: uplink

+ start vfs | caps: 150 | ram: 48M
  + provides | + service File_system
  + config
  | + vfs
  |   + rump | fs: ext2fs | ram: 10M
  |   + import
  |     + dir logs
  |       + inline test.log
  |         : First line log file!
  |         :
  |   + dir dev
  |     + dir pipe | + pipe
  |   + dir var
  |     + dir spool
  |       + dir rsyslog
  |         + ram
  |     + dir run
  |       + dir log | + ram
  |   + dir socket | + lwip | dhcp: yes
  | + default-policy | root: / | writeable: yes
  + route
    + service Block | + child nvme
    + service Nic   | + child nic_router
    + any-service
      + parent
      + any-child

+ start test-rsyslog | caps: 100 | ram: 3M
  + config
  | + arg | value: test-rsyslog
  | + arg | value: /logs/test.log
  | + arg | value: 1000
  | + libc | stdout: /dev/log | stderr: /dev/log | rtc: /dev/rtc
  | + vfs
  |   + dir dev
  |     + log
  |     + rtc
  |   + fs
  | + default-policy | root: / | writeable: yes
  + route
    + service File_system | + child vfs
    + service Rtc         | + child system_rtc
    + any-service
      + parent
      + any-child

+ start rsyslogd | caps: 520 | ram: 64M
  + config | ld_verbose: true | verbose: yes
  | + arg | value: rsyslogd
  | + arg | value: -n
  | + arg | value: -iNONE
  | x env RSYSLOG_DEBUG | : debug
  | + libc | stdout: /dev/log | stderr: /dev/log
  |        | rtc: /dev/rtc | socket: /socket | pipe: /dev/pipe
  |        | rng: /dev/random
  | + vfs
  |   + dir dev
  |     + jitterentropy random
  |     + jitterentropy urandom
  |     + log
  |     + null
  |     + rtc
  |   + dir etc
  |     + inline rsyslog.conf
  |       : module(load="imfile" PollingInterval="3")
  |       :
  |       : input(type="imfile" File="/logs/test.log"
  |       :       Tag="test_tag" Severity="error"
  |       :       Facility="local7")
  |       :
  |       : #global(workDirectory="/logs")
  |       : action(type="omfile" File="/dev/log")
  |       : action(type="omfwd"
  |       :        target="10.0.2.2"
  |       :        port="2342"
  |       :        protocol="udp"
  |       :        queue.type="LinkedList")
  |       :
  |       : *.* ~
  |   + fs
  + route
    + service File_system | + child vfs
    + service Rtc         | + child system_rtc
    + service Timer       | + child timer
    + any-service         | + parent
-}

install_config $config

build_boot_image [build_artifacts]

append qemu_args " -nographic -boot d "
append qemu_args " -device pcie-root-port,id=root_port1 "
append qemu_args " -drive id=nvme0,file=bin/rsyslog-ext2.raw,format=raw,if=none "
append qemu_args " -device nvme,drive=nvme0,serial=fnord,id=nvme0n1,bus=root_port1 "


run_genode_until forever
